#!/bin/bash

set -e

if [ $# -lt 2 ]; then
    >&2 echo "Needs 2 parameters (FROM and TO)"
    exit 1
fi

find_db() {
	ldb -a | grep -Eq "^$1$"
}

from=$1
to=$2

killodoo

if ! $(find_db $from); then
	>&2 echo "DB $from does not exist"
	exit 1
fi

if $(find_db $to); then
	dropdb $to
fi

if [ -d ~/.local/share/Odoo/filestore/$to/ ]; then
  rm -r ~/.local/share/Odoo/filestore/$to/
fi

createdb -T $from $to
mkdir ~/.local/share/Odoo/filestore/$to/
cp -r ~/.local/share/Odoo/filestore/$from/* ~/.local/share/Odoo/filestore/$to/
