#!/bin/bash

set -e

base_path="$HOME/src/all"
odoo_path="$base_path/odoo"
enterprise_path="$base_path/enterprise"
env_path="$HOME/odoo_env"

changeTo() {
	cd "$1"
	git checkout "$2"
	git clean -fdXq
}

changeTo "$odoo_path" "$1" &
changeTo "$enterprise_path" "$1" &

wait

changexenv "$1"

